In [1]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
import numpy as np
from sklearn.metrics import mean_squared_error
from random import random, seed
import sys
sys.path.append("../")
import functions as f
plt.style.use('seaborn-v0_8-whitegrid')
#plt.style.available
import seaborn as sns
import load_data as ld
import classes as cl

In [2]:
# Load simple data
X, y, x, a_true = ld.load_simple_data(100, 0.1)
# Initial beta
beta_init = np.random.randn(X.shape[1])
print(X.shape[1])
print(a_true)

3
[0.88114956 0.82005649 0.73665888]


In [3]:
betaOLS = f.beta_OLS(X, y)
betaRidge = f.beta_Ridge(X, y, 0.5)
print(beta_init)
print(betaOLS)
print(betaRidge)

[-1.22541231  1.12483019 -1.18774191]
[0.88378481 0.82957288 0.72425269]
[0.87919261 0.82554568 0.72457299]


In [4]:
#Task 1) plain gradient descent with and without ridge
#OLS)
gd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=100, optimizer='gd', gradient_method='analytical', lambda_param=0.1)
optimized_gd_beta = gd.optimize()
print(optimized_gd_beta)
ygd = optimized_gd_beta[0] + optimized_gd_beta[1]*x + optimized_gd_beta[2]*x**2
print(mean_squared_error(y, ygd))
#Ridge)
rgd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=100, optimizer='gd', gradient_method='analytical', lambda_param=0.1, cost_function='ridge')
optimized_rgd_beta = rgd.optimize()
print(optimized_rgd_beta)
yrgd = optimized_rgd_beta[0] + optimized_rgd_beta[1]*x + optimized_rgd_beta[2]*x**2
print(mean_squared_error(y, yrgd))

[0.26089698 0.95388038 0.89253865]
0.2731105568226006
[0.27542128 0.89161104 0.86313741]
0.2641180693645645


In [5]:
#task 2) momentum gradient descent with and without ridge and comparison to plain gradient descent
#OLS)
mgd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=100, optimizer='gd', gradient_method='analytical', lambda_param=0.1, momentum = 0.9)
optimized_mgd_beta = mgd.optimize()
print(optimized_mgd_beta)
ymgd = optimized_mgd_beta[0] + optimized_mgd_beta[1]*x + optimized_mgd_beta[2]*x**2
print(mean_squared_error(y, ymgd))
#Ridge)
rmgd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=100, optimizer='gd', gradient_method='analytical', lambda_param=0.1, cost_function='ridge', momentum = 0.9)
optimized_rmgd_beta = rmgd.optimize()
print(optimized_rmgd_beta)
yrmgd = optimized_rmgd_beta[0] + optimized_rmgd_beta[1]*x + optimized_rmgd_beta[2]*x**2
print(mean_squared_error(y, yrmgd))

#comparing with the above loss values, we clearly see faster convergence

[0.8888034  0.82885954 0.72834302]
0.01127364104208621
[0.80079571 0.75458433 0.72936325]
0.023232293923448836


In [7]:
#task 3) repeat for stochastic gradient descent and dicuss results with respect to batch size, number of epochs etc
#without momentum
#OLS)
gd = cl.StochasticGradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='sgd', gradient_method='analytical', lambda_param=0.1)
optimized_gd_beta = gd.optimize()
print(optimized_gd_beta)
ygd = optimized_gd_beta[0] + optimized_gd_beta[1]*x + optimized_gd_beta[2]*x**2
print(mean_squared_error(y, ygd))
#Ridge)
rgd = cl.StochasticGradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='sgd', gradient_method='analytical', lambda_param=0.1, cost_function='ridge')
optimized_rgd_beta = rgd.optimize()
print(optimized_rgd_beta)
yrgd = optimized_rgd_beta[0] + optimized_rgd_beta[1]*x + optimized_rgd_beta[2]*x**2
print(mean_squared_error(y, yrgd))
#with momentum
#OLS)
mgd = cl.StochasticGradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='sgd', gradient_method='analytical', lambda_param=0.1, momentum = 0.9)
optimized_mgd_beta = mgd.optimize()
print(optimized_mgd_beta)
ymgd = optimized_mgd_beta[0] + optimized_mgd_beta[1]*x + optimized_mgd_beta[2]*x**2
print(mean_squared_error(y, ymgd))
#Ridge)
rmgd = cl.StochasticGradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='sgd', gradient_method='analytical', lambda_param=0.1, cost_function='ridge', momentum = 0.9)
optimized_rmgd_beta = rmgd.optimize()
print(optimized_rmgd_beta)
yrmgd = optimized_rmgd_beta[0] + optimized_rmgd_beta[1]*x + optimized_rmgd_beta[2]*x**2
print(mean_squared_error(y, yrmgd))

#this clearly converges faster than standard gradient descent (here we have batch sizes 1/10th the size, and 10x the epochs,
#so the same amount of computations.

#testing various batch sizes and number of epochs using OLS without momentum
batch_sizes = [1, 5, 20]
epochsls = [20, 100, 1000]
cost_history = []
for batch_size in batch_sizes:
    for epochs in epochsls:
        gd = cl.StochasticGradientDescent(X, y, beta_init, learning_rate=0.01, epochs=epochs, optimizer='sgd', gradient_method='analytical', lambda_param=0.1, batch_size=batch_size)
        optimized_gd_beta = gd.optimize()
        print(optimized_gd_beta)
        ygd = optimized_gd_beta[0] + optimized_gd_beta[1]*x + optimized_gd_beta[2]*x**2
        cost_history.append((batch_size, epochs, mean_squared_error(y, ygd)))

for t in cost_history:
    print(f"Batch size: {t[0]}, Epochs: {t[1]}, Loss: {t[2]}")
#for this simple of a function, it seems that every single datapoint gives a gradient representative of the whole dataset
#that is shown by the batch_size increasing doesn't seem to matter much for the loss, while increasing epochs dramatically
#decreases the loss.

[0.87438311 0.83036964 0.72878924]
0.01122120238993803
[0.80506899 0.75783239 0.72770954]
0.022293161955824176
[0.88569882 0.83756458 0.72124937]
0.011245525459773037
[0.80079253 0.76183365 0.73346842]
0.02166172444647367
[-0.56968465  1.14375893 -0.20019443]
[0.32812029 0.89491222 0.86760618]
[0.89282688 0.8299781  0.72529652]
[-0.62871363  1.06069089 -0.34563259]
[0.27766815 0.93363299 0.86853585]
[0.88184548 0.83200338 0.7253477 ]
[-0.6007769   1.10099537 -0.13561428]
[0.24058679 0.92417854 0.91830655]
[0.87850238 0.83116379 0.72433132]
Batch size: 1, Epochs: 20, Loss: 7.030281394248226
Batch size: 1, Epochs: 100, Loss: 0.21599331125174054
Batch size: 1, Epochs: 1000, Loss: 0.011268597852969131
Batch size: 5, Epochs: 20, Loss: 8.441998483913887
Batch size: 5, Epochs: 100, Loss: 0.26445325161313
Batch size: 5, Epochs: 1000, Loss: 0.011173072021049488
Batch size: 20, Epochs: 20, Loss: 6.672553106064881
Batch size: 20, Epochs: 100, Loss: 0.2776301607898716
Batch size: 20, Epochs: 1000,

In [14]:
#task 4, using adagrad on all previous methods (don't test for ridge since it would simply bloat the code)
#OLS, no momentum, standard gradient descent
gd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='adagrad', gradient_method='analytical', lambda_param=0.1)
optimized_gd_beta = gd.optimize()
print(optimized_gd_beta)
ygd = optimized_gd_beta[0] + optimized_gd_beta[1]*x + optimized_gd_beta[2]*x**2
print(mean_squared_error(y, ygd))
    #repeat with 100x higher epochs to show that adagrad slows down convergence
gd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=100000, optimizer='adagrad', gradient_method='analytical', lambda_param=0.1)
optimized_gd_beta = gd.optimize()
print(optimized_gd_beta)
ygd = optimized_gd_beta[0] + optimized_gd_beta[1]*x + optimized_gd_beta[2]*x**2
print(mean_squared_error(y, ygd))
#OLS, momentum, standard gradient descent
mgd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='adagrad', gradient_method='analytical', lambda_param=0.1, momentum = 0.9)
optimized_mgd_beta = mgd.optimize()
print(optimized_mgd_beta)
ymgd = optimized_mgd_beta[0] + optimized_mgd_beta[1]*x + optimized_mgd_beta[2]*x**2
print(mean_squared_error(y, ymgd))
#OLS, momentum, stochastic standard gradient descent
gd = cl.StochasticGradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='adagrad', gradient_method='analytical', lambda_param=0.1)
optimized_gd_beta = gd.optimize()
print(optimized_gd_beta)
ygd = optimized_gd_beta[0] + optimized_gd_beta[1]*x + optimized_gd_beta[2]*x**2
print(mean_squared_error(y, ygd))
#OLS, momentum, stochastic standard gradient descent
mgd = cl.StochasticGradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='adagrad', gradient_method='analytical', lambda_param=0.1, momentum = 0.9)
optimized_mgd_beta = mgd.optimize()
print(optimized_mgd_beta)
ymgd = optimized_mgd_beta[0] + optimized_mgd_beta[1]*x + optimized_mgd_beta[2]*x**2
print(mean_squared_error(y, ymgd))


#so we see that adagrad heavily slows down convergence. It can be balanced out by using momentum,
#as we see the implementations with momentum converge much faster.

[-0.64350203  0.84227052 -0.60711252]
10.852616470567828
[0.86515627 0.83041595 0.73453607]
0.011400314778876468
[0.85634876 0.83082015 0.73923755]
0.01167183728398292
[-0.65442168  1.0723386  -0.70922662]
11.994761205429096
[0.95040871 0.82886354 0.67653092]
0.0150786043134716


In [ ]:


mgd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='gd', gradient_method='analytical', lambda_param=0.1, momentum = 0.9)
optimized_mgd_beta = mgd.optimize()

agd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='adagrad', gradient_method='analytical', lambda_param=0.1)
optimized_agd_beta = agd.optimize()

magd = cl.GradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='adagrad', gradient_method='analytical', lambda_param=0.1, momentum = 0.9)
optimized_magd_beta = magd.optimize()

sgd = cl.StochasticGradientDescent(X, y, beta_init, learning_rate=0.01, epochs=1000, optimizer='adam', gradient_method='analytical')
optimized_sgd_beta = sgd.optimize()

print(optimized_mgd_beta)
print(optimized_agd_beta)
print(optimized_magd_beta)
print(optimized_sgd_beta)

In [ ]:
ymgd = optimized_mgd_beta[0] + optimized_mgd_beta[1]*x + optimized_mgd_beta[2]*x**2
yagd = optimized_agd_beta[0] + optimized_agd_beta[1]*x + optimized_agd_beta[2]*x**2
ymagd = optimized_magd_beta[0] + optimized_magd_beta[1]*x + optimized_magd_beta[2]*x**2


ysgd = optimized_sgd_beta[0] + optimized_sgd_beta[1]*x + optimized_sgd_beta[2]*x**2

print(mean_squared_error(y, ymgd))
print(mean_squared_error(y, yagd))
#adagrad converges slower. For higher epochs it converges similarly to the others
print(mean_squared_error(y, ymagd))
print(mean_squared_error(y, ysgd))

In [ ]:
#plotting
sort_inds = np.argsort(x)
plt.plot(x[sort_inds], y[sort_inds], label='Datapoints')
plt.plot(x[sort_inds], ygd[sort_inds], label='Gradient Descent')
plt.plot(x[sort_inds], ysgd[sort_inds], label='Stochastic Gradient Descent')
plt.xlabel('X')
plt.ylabel('y')
plt.legend()
plt.show()